import { useEffect, useState } from "react";
import { getMyArtists, uploadMyArtistImage } from "../services/artistWorkspace.service";
import { createMyArtistMedia, deleteMyArtistMedia, getMyArtistMedia, updateMyArtistMedia } from "../services/artistMedia.service";

export default function ArtistMediaPage() {
  const [artists, setArtists] = useState([]); const [artistId, setArtistId] = useState(""); const [items, setItems] = useState([]); const [limits, setLimits] = useState({ photo: 12, video_external: 6 }); const [video, setVideo] = useState({ url: "", title: "", thumbnailUrl: "" }); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { getMyArtists().then((data) => { setArtists(data); if (data[0]) setArtistId(data[0].id); }); }, []);
  async function load() { if (!artistId) return; try { const data = await getMyArtistMedia(artistId); setItems(data.items); setLimits(data.limits); } catch (error) { setMessage(error?.response?.data?.message || "Nao foi possivel carregar a galeria."); } }
  useEffect(() => { load(); }, [artistId]);
  async function addPhoto(file) { if (!file) return; setBusy(true); try { const asset = await uploadMyArtistImage({ artistId, file, kind: "gallery" }); await createMyArtistMedia(artistId, { type: "photo", url: asset.publicUrl || asset.url, storageProvider: "r2", storageKey: asset.storageKey || asset.path, mimeType: asset.mimeType, fileSizeBytes: asset.fileSizeBytes || asset.size, altText: file.name, sortOrder: items.filter((item) => item.type === "photo").length }); setMessage("Foto adicionada."); await load(); } catch (error) { setMessage(error?.response?.data?.message || "Nao foi possivel adicionar a foto."); } finally { setBusy(false); } }
  async function addVideo(event) { event.preventDefault(); setBusy(true); try { await createMyArtistMedia(artistId, { type: "video_external", url: video.url, title: video.title || null, thumbnailUrl: video.thumbnailUrl || null, sortOrder: items.filter((item) => item.type === "video_external").length }); setVideo({ url: "", title: "", thumbnailUrl: "" }); setMessage("Video adicionado."); await load(); } catch (error) { setMessage(error?.response?.data?.message || "Nao foi possivel adicionar o video."); } finally { setBusy(false); } }
  async function toggle(item) { await updateMyArtistMedia(item.id, { isPublished: !item.isPublished }); await load(); }
  async function remove(item) { if (!window.confirm("Remover este item da galeria?")) return; await deleteMyArtistMedia(item.id); await load(); }
  const photoCount = items.filter((item) => item.type === "photo").length; const videoCount = items.filter((item) => item.type === "video_external").length;
  return <section className="screen artist-workspace-screen"><header className="page-header"><h2>Fotos e vídeos</h2><p>Mostre presença de palco sem transformar o perfil num depósito de arquivos.</p></header>{message ? <p className="clean-card">{message}</p> : null}{artists.length ? <><div className="clean-card artist-workspace-picker"><select value={artistId} onChange={(event) => setArtistId(event.target.value)}>{artists.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><span>{photoCount}/{limits.photo} fotos · {videoCount}/{limits.video_external} vídeos</span></div><div className="ads-hard-grid ads-hard-forms"><section className="clean-card"><h3>Adicionar foto</h3><p className="meta-line">JPG, PNG ou WebP, até 5 MB.</p><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy || photoCount >= limits.photo} onChange={(event) => addPhoto(event.target.files?.[0])}/></section><form className="clean-card venue-form" onSubmit={addVideo}><h3>Adicionar vídeo externo</h3><input type="url" required placeholder="Link do YouTube, Vimeo, Instagram ou TikTok" value={video.url} onChange={(event) => setVideo({ ...video, url: event.target.value })}/><input placeholder="Título" value={video.title} onChange={(event) => setVideo({ ...video, title: event.target.value })}/><input type="url" placeholder="Miniatura (opcional)" value={video.thumbnailUrl} onChange={(event) => setVideo({ ...video, thumbnailUrl: event.target.value })}/><button className="btn-primary" disabled={busy || videoCount >= limits.video_external}>Adicionar vídeo</button></form></div><div className="artist-media-admin-grid">{items.map((item) => <article className="clean-card" key={item.id}>{item.type === "photo" ? <img src={item.url} alt={item.altText || "Foto"}/> : <a href={item.url} target="_blank" rel="noreferrer">{item.thumbnailUrl ? <img src={item.thumbnailUrl} alt=""/> : <strong>{item.title || "Abrir vídeo"}</strong>}</a>}<p>{item.title || (item.type === "photo" ? "Foto" : "Vídeo")}</p><div className="form-actions-inline"><button className="chip" onClick={() => toggle(item)}>{item.isPublished ? "Ocultar" : "Publicar"}</button><button className="chip chip-danger" onClick={() => remove(item)}>Remover</button></div></article>)}</div></> : <p className="empty">Nenhum perfil sob sua gestão.</p>}</section>;
}
