import { useEffect, useState } from "react";
import BackLink from "../components/common/BackLink";
import { getMyArtists } from "../services/artistWorkspace.service";
import { getArtistTeam, inviteArtistTeamMember, revokeArtistTeamMember, updateArtistTeamMember } from "../services/artistTeam.service";

const ROLE_LABELS = { owner: "Proprietário", manager: "Gestor", editor: "Editor", viewer: "Leitor" };
const STATUS_LABELS = { active: "Ativo", invited: "Convite pendente", suspended: "Suspenso", revoked: "Revogado" };

export default function ArtistTeamPage() {
  const [artists, setArtists] = useState([]); const [artistId, setArtistId] = useState("");
  const [team, setTeam] = useState([]); const [canManage, setCanManage] = useState(false);
  const [invite, setInvite] = useState({ email: "", role: "manager" }); const [message, setMessage] = useState("");

  useEffect(() => { getMyArtists().then((items) => { setArtists(items); setArtistId(items[0]?.id || ""); }).catch(() => setMessage("Não foi possível carregar seus artistas.")); }, []);
  async function load() { if (!artistId) return; try { const data = await getArtistTeam(artistId); setTeam(data.items); setCanManage(data.canManage); } catch (error) { setTeam([]); setCanManage(false); setMessage(error?.response?.data?.message || "Não foi possível carregar a equipe."); } }
  useEffect(() => { load(); }, [artistId]);
  async function submit(event) { event.preventDefault(); try { await inviteArtistTeamMember(artistId, invite); setInvite({ email: "", role: "manager" }); setMessage("Convite enviado."); await load(); } catch (error) { setMessage(error?.response?.data?.message || "Não foi possível enviar o convite."); } }
  async function changeMember(item, payload) { try { await updateArtistTeamMember(item.id, payload); setMessage("Acesso atualizado."); await load(); } catch (error) { setMessage(error?.response?.data?.message || "Não foi possível atualizar o acesso."); } }
  async function removeMember(item) { if (!window.confirm(`Remover ${item.user.firstName} da equipe?`)) return; try { await revokeArtistTeamMember(item.id); setMessage("Integrante removido."); await load(); } catch (error) { setMessage(error?.response?.data?.message || "Não foi possível remover o integrante."); } }

  return <section className="screen artist-team-screen"><BackLink to="/settings">Voltar ao Hub de Gestão</BackLink><header className="page-header"><h2>Equipe do artista</h2><p>Distribua o trabalho do perfil sem compartilhar senhas.</p></header>{artists.length ? <div className="clean-card artist-workspace-picker"><label>Artista<select value={artistId} onChange={(event) => setArtistId(event.target.value)}>{artists.map((artist) => <option value={artist.id} key={artist.id}>{artist.name}</option>)}</select></label><span>{team.filter((item) => ["active", "invited"].includes(item.status)).length}/10 integrantes</span></div> : null}{message ? <p className="clean-card">{message}</p> : null}{canManage ? <form className="clean-card artist-team-invite" onSubmit={submit}><h3>Convidar integrante</h3><p className="meta-line">A pessoa precisa ter uma conta no 77Gira. Proprietários são definidos apenas por processo de reivindicação.</p><div><input required type="email" placeholder="E-mail da conta" value={invite.email} onChange={(event) => setInvite({ ...invite, email: event.target.value })}/><select value={invite.role} onChange={(event) => setInvite({ ...invite, role: event.target.value })}><option value="manager">Gestor</option><option value="editor">Editor</option><option value="viewer">Leitor</option></select><button className="btn-primary">Enviar convite</button></div></form> : null}<div className="artist-team-list">{team.filter((item) => item.status !== "revoked").map((item) => <article className="clean-card" key={item.id}><div className="artist-team-avatar">{item.user.avatarUrl ? <img src={item.user.avatarUrl} alt=""/> : <span>{item.user.firstName?.[0]}{item.user.lastName?.[0]}</span>}</div><div className="artist-team-identity"><strong>{item.user.firstName} {item.user.lastName}</strong><small>{item.user.email}</small></div><div className="artist-team-controls">{canManage && item.role !== "owner" ? <select value={item.role} onChange={(event) => changeMember(item, { role: event.target.value })}><option value="manager">Gestor</option><option value="editor">Editor</option><option value="viewer">Leitor</option></select> : <span>{ROLE_LABELS[item.role]}</span>}<small>{STATUS_LABELS[item.status]}</small></div>{canManage && item.role !== "owner" ? <button className="chip chip-danger" onClick={() => removeMember(item)}>Remover</button> : null}</article>)}</div></section>;
}
